
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.HPaned hpaned3;

	private global::Gtk.Notebook notebook2;

	private global::Gtk.Label label2;

	private global::Gtk.HPaned hpaned4;

	private global::Gtk.ScrolledWindow scrolledwindow3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Button btnTest;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar2\'/></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox3.Add(this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'/></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox3.Add(this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hpaned3 = new global::Gtk.HPaned();
		this.hpaned3.CanFocus = true;
		this.hpaned3.Name = "hpaned3";
		this.hpaned3.Position = 153;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.notebook2 = new global::Gtk.Notebook();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w5 = new global::Gtk.Label();
		w5.Visible = true;
		this.notebook2.Add(w5);
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
		this.notebook2.SetTabLabel(w5, this.label2);
		this.label2.ShowAll();
		this.hpaned3.Add(this.notebook2);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned3[this.notebook2]));
		w6.Resize = false;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.hpaned4 = new global::Gtk.HPaned();
		this.hpaned4.CanFocus = true;
		this.hpaned4.Name = "hpaned4";
		this.hpaned4.Position = 356;
		// Container child hpaned4.Gtk.Paned+PanedChild
		this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow3.CanFocus = true;
		this.scrolledwindow3.Name = "scrolledwindow3";
		this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		this.hpaned4.Add(this.scrolledwindow3);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.hpaned4[this.scrolledwindow3]));
		w7.Resize = false;
		// Container child hpaned4.Gtk.Paned+PanedChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnTest = new global::Gtk.Button();
		this.btnTest.CanFocus = true;
		this.btnTest.Name = "btnTest";
		this.btnTest.UseUnderline = true;
		this.btnTest.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.vbox4.Add(this.btnTest);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.btnTest]));
		w8.Position = 0;
		w8.Fill = false;
		this.hpaned4.Add(this.vbox4);
		this.hpaned3.Add(this.hpaned4);
		this.vbox2.Add(this.hpaned3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hpaned3]));
		w11.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox2.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.statusbar1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 732;
		this.DefaultHeight = 488;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnTest.Clicked += new global::System.EventHandler(this.TestButtonClick);
	}
}
