
// This file has been generated by the GUI designer. Do not modify.
namespace MediaProjector
{
	public partial class DisplayWindow
	{
		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MediaProjector.DisplayWindow
			this.Name = "MediaProjector.DisplayWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("DisplayWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(5));
			this.Resizable = false;
			// Container child MediaProjector.DisplayWindow.Gtk.Container+ContainerChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.Add(this.label3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
